services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./stub:/srv/stub # путь до директории с заглушкой
    networks:
      xray-net:
        ipv4_address: 172.100.100.101 # Прибиваем ip. Telemt не умеет резолвить адрес прокси

  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - ./config.json:/etc/xray/config.json
    restart: unless-stopped
    networks:
      xray-net:
        ipv4_address: 172.100.100.100

  v2ray-exporter:
    image: wi1dcard/v2ray-exporter:master
    container_name: v2ray-exporter
    command:
      - "--v2ray-endpoint=xray:8080"
    ports:
      - "9550:9550"
    depends_on:
      - xray
    networks:
      - xray-net

  telemt:
    image: whn0thacked/telemt-docker:latest
    container_name: telemt
    restart: unless-stopped
    networks:
      - xray-net
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      RUST_LOG: "info"
    volumes:
      - ./telemt_data:/etc/telemt
      - ./telemt.toml:/etc/telemt.toml:ro
    ports:
      - "443:443/tcp"
      - "100.64.64.5:9092:9090/tcp"
    extra_hosts:
      - "<domain>:172.100.100.101"

networks:
  xray-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.100.0/24