services:
  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - ./config.json:/etc/xray/config.json
      - /var/log/xray:/var/log/xray
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - caddy_data:/caddy_data
    restart: unless-stopped
    networks:
      xray-net:
        ipv4_address: 172.100.100.100

  v2ray-exporter:
    image: wi1dcard/v2ray-exporter:master
    container_name: v2ray-exporter
    command:
      - "--v2ray-endpoint=xray:8080"
    ports:
      - "1.1.1.1:1111:1111" #you ip and port for metrics
    depends_on:
      - xray
    networks:
      - xray-net

networks:
  xray-net:
    external: true

volumes:
  caddy_data:
    external: true
